app:
  version: 1

server:
  servlet:
    context-path: /quizmarkt-base
  port: 9092

spring:
  cache:
    type: caffeine
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quizmarkt_db
    username: root
    password: admin

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

webService:
  userManagement:
    endpoint: ${WEB_SERVICE_USER_MANAGEMENT_ENDPOINT:http://localhost:9091}

jwt:
  secret:
    key: ${JWT_SECRET}